name: Sync mirror-3 branch

on:
  schedule:
    - cron: '0 1 * * 0' # Runs weekly, 1 hour after the first workflow
  workflow_dispatch: # Allows manual trigger

jobs:
  update-mirror-3:
    runs-on: ubuntu-latest
    steps:
      - name: Set committer identity
        run: |
          git config --global user.email "orcnog@gmail.com" # Your email
          git config --global user.name "orcnog" # Your name

      - name: Checkout orcnog.github.io repo
        uses: actions/checkout@v3
        with:
          repository: orcnog/orcnog.github.io
          ref: mirror-3
          fetch-depth: 0  # Ensures full history is fetched

      - name: Fetch mirror-3 repository
        run: git fetch https://github.com/orcnog/5etools-mirror-3.git main

      - name: Reset to 5etools-mirror-3/main
        run: git reset --hard FETCH_HEAD

      - name: Force push changes to mirror-3 branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Using the PAT for authentication
        run: git push origin mirror-3 --force
